framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Doctrine's metadata.
        #auto_mapping:
        #    App\Entity\: []
        App\Entity\Calculator:
            properties:
                firstNumber:
                    - NotBlank: ~
                secondNumber:
                    - NotBlank: ~
                operand:
                    - NotBlank: ~
                    - Choice: [add, subtract, multiply, divide]

when@test:
    framework:
        validation:
            not_compromised_password: false
